site_name: Céu-libuv v0.20 - Reference Manual
theme:     readthedocs
#site_dir:  site/v0.20

pages:
- Home:                    index.md
- Introduction:            010-introduction.md
- Mode of Operation:       020-modes.md
- Input Events:            030-inputs.md
- Data Abstractions:       040-datas.md
- Code/Await Abstractions: 060-code-awaits.md
- License:                 license.md

