site_name: Céu-libuv v0.20 - Reference Manual
theme:     readthedocs
#site_dir:  site/v0.20

markdown_extensions:
    - markdown_include.include:
        base_path: docs
    - toc:
        permalink: True
    #- codehilite(linenums=true)

pages:
    - Introduction:         'index.md'
    - Mode of Operation:    'modes/index.md'
    - File System:          'fs/index.md'
    - Stream:               'stream/index.md'
    - TCP:                  'tcp/index.md'
    - License:              'license.md'
